# Generated by Django 4.2.1 on 2023-05-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('p_phone', models.IntegerField(max_length=10)),
                ('p_email', models.EmailField(max_length=100)),
                ('booking_date', models.DateField()),
                ('booken_on', models.DateField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.doctors')),
            ],
        ),
    ]
